import markdown2
from xhtml2pdf import pisa
from io import BytesIO

def markdown_to_pdf(markdown_text):
    """
    Converts markdown text to a professional PDF document.
    """
    # 1. Convert Markdown to HTML
    html_content = markdown2.markdown(markdown_text, extras=["tables", "fenced-code-blocks"])
    
    # 2. Add professional CSS styling
    styled_html = f"""
    <html>
        <head>
            <style>
                body {{ font-family: Helvetica, Arial, sans-serif; margin: 40px; color: #333; line-height: 1.5; }}
                h1 {{ color: #007bff; border-bottom: 2px solid #007bff; padding-bottom: 10px; }}
                h2 {{ color: #343a40; margin-top: 20px; border-bottom: 1px solid #dee2e6; }}
                table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
                th, td {{ border: 1px solid #dee2e6; padding: 8px; text-align: left; }}
                th {{ background-color: #f8f9fa; font-weight: bold; }}
                code {{ background-color: #f4f4f4; padding: 2px 4px; border-radius: 4px; font-family: monospace; }}
                .footer {{ text-align: center; font-size: 10px; color: #777; margin-top: 50px; }}
            </style>
        </head>
        <body>
            {html_content}
            <div class="footer">Generated by AI Data Insight Reporter</div>
        </body>
    </html>
    """
    
    # 3. Create PDF Buffer
    pdf_buffer = BytesIO()
    pisa_status = pisa.CreatePDF(styled_html, dest=pdf_buffer)
    
    if pisa_status.err:
        return None
        
    pdf_buffer.seek(0)
    return pdf_buffer